stages:
  - deploy
deploy:
  image: ubuntu:18.04
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_12.x | bash
    - apt-get install -y nodejs
  script:
    - touch .env
    - echo VUE_APP_CMS_DATOCMS_API_TOKEN=$DATOCMS_API_KEY >> .env
    - cat .env
    - npm install
    - npm run build
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete dist/ www/; bye"
