local_backend: true
backend:
  name: git-gateway
  branch: main
  cms_label_prefix: "cms/"
publish_mode: editorial_workflow
media_folder: "/public/images"
public_folder: "/images"
collections:
  - name: "about-me"
    label: "About Me"
    folder: "src/content/about-me"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: "title"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["title"]
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Content", name: "body", widget: "markdown", required: true }
  - name: "project"
    label: "Project"
    folder: "src/content/project"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: "title"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["sort", "title"]
    fields:
      - { label: "Sort", name: "sort", widget: "number", value_type: "int", default: 1, min: 1, required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - label: "Screenshot"
        name: "screenshot"
        widget: "object"
        fields:
          - { label: "Image", name: "src", widget: "image", required: true }
          - { label: "Alt", name: "alt", widget: "string", required: true }
      - label: "Technologies"
        name: "technologies"
        widget: "list"
        minimize_collapsed: false
        collapsed: true
        field: { label: "Name", name: "name", widget: "string" }
        required: true
      - { label: "Github URL", name: "githubUrl", widget: "string", required: true }
      - { label: "Demo URL", name: "demoUrl", widget: "string", required: true }
      - { label: "Content", name: "body", widget: "text", required: true }
  - name: "socialLink"
    label: "Social Link"
    folder: "src/content/social-link"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: "title"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["sort", "title"]
    fields:
      - { label: "Sort", name: "sort", widget: "number", value_type: "int", default: 1, min: 1, required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Link", name: "link", widget: "string", required: true }
      - { label: "Alt", name: "alt", widget: "string", required: true }
      - { label: "Icon", name: "icon", widget: "string", required: true }
      - { label: "Open in new tab", name: "newTab", widget: "boolean", default: true, required: true }
  - name: "uses"
    label: "Uses"
    folder: "src/content/uses"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: "title"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["title"]
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Content", name: "body", widget: "markdown", required: true }
