backend:
  name: github
  branch: main
  repo: teziovsky/jakubsoboczynski

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "social_links"
    label: "Social Links"
    folder: "social_links"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "about_me"
    label: "About Me"
    folder: "about_me"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }