backend:
  name: github
  branch: main
  repo: teziovsky/jakubsoboczynski

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "social_links"
    label: "Social Links"
    folder: "content/social_links"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Sort", name: "sort", widget: "number" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Icon", name: "icon", widget: "string" }

  - name: "about_me"
    label: "About Me"
    folder: "content/about_me"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    folder: "blog/posts/{{category}}"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }